services:
  crud_database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crud
    ports:
      - '5429:5432'
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  crud_redis:
    image: redis
    ports:
      - '6379:6379'
